#define TK_SEMI                             1
#define TK_EXPLAIN                          2
#define TK_QUERY                            3
#define TK_PLAN                             4
#define TK_BEGIN                            5
#define TK_TRANSACTION                      6
#define TK_DEFERRED                         7
#define TK_IMMEDIATE                        8
#define TK_EXCLUSIVE                        9
#define TK_COMMIT                          10
#define TK_END                             11
#define TK_ROLLBACK                        12
#define TK_SAVEPOINT                       13
#define TK_RELEASE                         14
#define TK_TO                              15
#define TK_TABLE                           16
#define TK_CREATE                          17
#define TK_IF                              18
#define TK_NOT                             19
#define TK_EXISTS                          20
#define TK_TEMP                            21
#define TK_LP                              22
#define TK_RP                              23
#define TK_AS                              24
#define TK_COMMA                           25
#define TK_WITHOUT                         26
#define TK_ABORT                           27
#define TK_ACTION                          28
#define TK_AFTER                           29
#define TK_ANALYZE                         30
#define TK_ASC                             31
#define TK_ATTACH                          32
#define TK_BEFORE                          33
#define TK_BY                              34
#define TK_CASCADE                         35
#define TK_CAST                            36
#define TK_CONFLICT                        37
#define TK_DATABASE                        38
#define TK_DESC                            39
#define TK_DETACH                          40
#define TK_EACH                            41
#define TK_FAIL                            42
#define TK_OR                              43
#define TK_AND                             44
#define TK_IS                              45
#define TK_ISNOT                           46
#define TK_MATCH                           47
#define TK_LIKE_KW                         48
#define TK_BETWEEN                         49
#define TK_IN                              50
#define TK_ISNULL                          51
#define TK_NOTNULL                         52
#define TK_NE                              53
#define TK_EQ                              54
#define TK_GT                              55
#define TK_LE                              56
#define TK_LT                              57
#define TK_GE                              58
#define TK_ESCAPE                          59
#define TK_LBRACE                          60
#define TK_RBRACE                          61
#define TK_LBRACKET                        62
#define TK_RBRACKET                        63
#define TK_COLON                           64
#define TK_JOIN_ARROW                      65
#define TK_REV_JOIN_ARROW                  66
#define TK_RECURSE                         67
#define TK_XML_LT                          68
#define TK_XML_END_LT                      69
#define TK_XML_SLASH_GT                    70
#define TK_XML_GT                          71
#define TK_XML_TEXT                        72
#define TK_ID                              73
#define TK_COLUMNKW                        74
#define TK_DO                              75
#define TK_FOR                             76
#define TK_IGNORE                          77
#define TK_INITIALLY                       78
#define TK_INSTEAD                         79
#define TK_NO                              80
#define TK_KEY                             81
#define TK_OF                              82
#define TK_OFFSET                          83
#define TK_PRAGMA                          84
#define TK_RAISE                           85
#define TK_RECURSIVE                       86
#define TK_REPLACE                         87
#define TK_RESTRICT                        88
#define TK_ROW                             89
#define TK_ROWS                            90
#define TK_TRIGGER                         91
#define TK_VACUUM                          92
#define TK_VIEW                            93
#define TK_VIRTUAL                         94
#define TK_WITH                            95
#define TK_NULLS                           96
#define TK_FIRST                           97
#define TK_LAST                            98
#define TK_CURRENT                         99
#define TK_FOLLOWING                      100
#define TK_PARTITION                      101
#define TK_PRECEDING                      102
#define TK_RANGE                          103
#define TK_UNBOUNDED                      104
#define TK_EXCLUDE                        105
#define TK_GROUPS                         106
#define TK_OTHERS                         107
#define TK_TIES                           108
#define TK_WITHIN                         109
#define TK_GENERATED                      110
#define TK_ALWAYS                         111
#define TK_MATERIALIZED                   112
#define TK_REINDEX                        113
#define TK_RENAME                         114
#define TK_CTIME_KW                       115
#define TK_ANY                            116
#define TK_BITAND                         117
#define TK_BITOR                          118
#define TK_LSHIFT                         119
#define TK_RSHIFT                         120
#define TK_PLUS                           121
#define TK_MINUS                          122
#define TK_STAR                           123
#define TK_SLASH                          124
#define TK_REM                            125
#define TK_CONCAT                         126
#define TK_PTR                            127
#define TK_COLLATE                        128
#define TK_BITNOT                         129
#define TK_ON                             130
#define TK_INDEXED                        131
#define TK_STRING                         132
#define TK_JOIN_KW                        133
#define TK_CONSTRAINT                     134
#define TK_DEFAULT                        135
#define TK_NULL                           136
#define TK_PRIMARY                        137
#define TK_UNIQUE                         138
#define TK_CHECK                          139
#define TK_REFERENCES                     140
#define TK_AUTOINCR                       141
#define TK_INSERT                         142
#define TK_DELETE                         143
#define TK_UPDATE                         144
#define TK_SET                            145
#define TK_DEFERRABLE                     146
#define TK_FOREIGN                        147
#define TK_DROP                           148
#define TK_UNION                          149
#define TK_ALL                            150
#define TK_EXCEPT                         151
#define TK_INTERSECT                      152
#define TK_SELECT                         153
#define TK_INTEGER                        154
#define TK_FROM                           155
#define TK_DOT                            156
#define TK_VALUES                         157
#define TK_DISTINCT                       158
#define TK_JOIN                           159
#define TK_USING                          160
#define TK_ORDER                          161
#define TK_GROUP                          162
#define TK_HAVING                         163
#define TK_LIMIT                          164
#define TK_WHERE                          165
#define TK_RETURNING                      166
#define TK_INTO                           167
#define TK_NOTHING                        168
#define TK_FLOAT                          169
#define TK_BLOB                           170
#define TK_VARIABLE                       171
#define TK_CASE                           172
#define TK_WHEN                           173
#define TK_THEN                           174
#define TK_ELSE                           175
#define TK_INDEX                          176
#define TK_ALTER                          177
#define TK_ADD                            178
#define TK_WINDOW                         179
#define TK_OVER                           180
#define TK_FILTER                         181
#define TK_COLUMN                         182
#define TK_AGG_FUNCTION                   183
#define TK_AGG_COLUMN                     184
#define TK_TRUEFALSE                      185
#define TK_FUNCTION                       186
#define TK_UPLUS                          187
#define TK_UMINUS                         188
#define TK_TRUTH                          189
#define TK_REGISTER                       190
#define TK_VECTOR                         191
#define TK_SELECT_COLUMN                  192
#define TK_IF_NULL_ROW                    193
#define TK_ASTERISK                       194
#define TK_SPAN                           195
#define TK_ERROR                          196
#define TK_QNUMBER                        197
#define TK_SPACE                          198
#define TK_COMMENT                        199
#define TK_ILLEGAL                        200
